#!/usr/bin/expect -f
set password "@Tony1022837069"

spawn rsync -avz --exclude node_modules --exclude *.exp --exclude .git --exclude .DS_Store --exclude .env --delete ./ root@72.62.160.140:~/boosis-bot/
expect {
    "password:" {
        send "$password\r"
        exp_continue
    }
    eof
}

spawn ssh root@72.62.160.140 "docker restart boosis-bot"
expect {
    "password:" {
        send "$password\r"
        exp_continue
    }
    eof
}
